# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: steven
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phantom_mask
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: